# Generated by Django 3.2.25 on 2024-04-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_auto_20240405_0044'),
        ('judge', '0145_site_data_batch_prerequisites'),
    ]

    operations = [
    ]
